-- Setup unico para PostgreSQL - BFA Numerico Sumas y Multiplicaciones
--
-- Ejecutar desde la raiz del proyecto:
-- psql -U postgres -d postgres -f "scripts\setup_postgres_bfa.sql"
--
-- Este script:
-- 1. Crea la base "Estudiantedb" si no existe.
-- 2. Se conecta a "Estudiantedb".
-- 3. Crea las tablas principales si faltan.
-- 4. Inserta registrador, tests y las 50 preguntas.
--
-- Nota: el usuario candidato demo lo crea la aplicacion al arrancar
-- usando DatosInicialesListener, para que la contrasena quede cifrada con BCrypt.

\set ON_ERROR_STOP on

SELECT 'CREATE DATABASE "Estudiantedb" WITH ENCODING ''UTF8'''
WHERE NOT EXISTS (
    SELECT 1 FROM pg_database WHERE datname = 'Estudiantedb'
)\gexec

\connect "Estudiantedb"

BEGIN;

CREATE TABLE IF NOT EXISTS registrador (
    idregistrador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    apellidos VARCHAR(50),
    contrasena VARCHAR(100),
    correo VARCHAR(100),
    fecharegistro TIMESTAMP,
    nombreusuario VARCHAR(30),
    nombres VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS usuario (
    idusuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    apellidos VARCHAR(50),
    contrasena VARCHAR(100),
    correo VARCHAR(100),
    fecharegistro TIMESTAMP,
    nombreusuario VARCHAR(30),
    nombres VARCHAR(50),
    edad INTEGER NOT NULL DEFAULT 18
);

CREATE TABLE IF NOT EXISTS testnumerico (
    idtestnumerico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    descripcion VARCHAR(255),
    nombre VARCHAR(100),
    tipotest VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS intentotest (
    idintentotest BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aciertos INTEGER NOT NULL DEFAULT 0,
    cantidadpreguntas INTEGER NOT NULL DEFAULT 0,
    errores INTEGER NOT NULL DEFAULT 0,
    estado VARCHAR(15),
    fechafin TIMESTAMP,
    fechainicio TIMESTAMP,
    sinresponder INTEGER NOT NULL DEFAULT 0,
    puntajedirecto INTEGER NOT NULL DEFAULT 0,
    testnumerico_idtestnumerico BIGINT,
    usuario_idusuario BIGINT
);

CREATE TABLE IF NOT EXISTS pregunta (
    idpregunta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    fechacreacion TIMESTAMP,
    numeropregunta INTEGER NOT NULL,
    operacion VARCHAR(100),
    respuestacorrecta VARCHAR(1),
    resultadomostrado INTEGER NOT NULL,
    registrador_idregistrador BIGINT,
    testnumerico_idtestnumerico BIGINT
);

CREATE TABLE IF NOT EXISTS respuesta (
    idrespuesta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    respuestamarcada VARCHAR(1),
    intentotest_idintentotest BIGINT,
    pregunta_idpregunta BIGINT
);

ALTER TABLE testnumerico
    ADD COLUMN IF NOT EXISTS tipotest VARCHAR(20);

ALTER TABLE intentotest
    ADD COLUMN IF NOT EXISTS puntajedirecto INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS ux_registrador_correo
    ON registrador (correo)
    WHERE correo IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_registrador_nombreusuario
    ON registrador (nombreusuario)
    WHERE nombreusuario IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_correo
    ON usuario (correo)
    WHERE correo IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_nombreusuario
    ON usuario (nombreusuario)
    WHERE nombreusuario IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_pregunta_test_numero
    ON pregunta (testnumerico_idtestnumerico, numeropregunta)
    WHERE testnumerico_idtestnumerico IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intentotest_usuario') THEN
        ALTER TABLE intentotest
            ADD CONSTRAINT fk_intentotest_usuario
            FOREIGN KEY (usuario_idusuario) REFERENCES usuario(idusuario);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_intentotest_testnumerico') THEN
        ALTER TABLE intentotest
            ADD CONSTRAINT fk_intentotest_testnumerico
            FOREIGN KEY (testnumerico_idtestnumerico) REFERENCES testnumerico(idtestnumerico);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pregunta_registrador') THEN
        ALTER TABLE pregunta
            ADD CONSTRAINT fk_pregunta_registrador
            FOREIGN KEY (registrador_idregistrador) REFERENCES registrador(idregistrador);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pregunta_testnumerico') THEN
        ALTER TABLE pregunta
            ADD CONSTRAINT fk_pregunta_testnumerico
            FOREIGN KEY (testnumerico_idtestnumerico) REFERENCES testnumerico(idtestnumerico);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_respuesta_intentotest') THEN
        ALTER TABLE respuesta
            ADD CONSTRAINT fk_respuesta_intentotest
            FOREIGN KEY (intentotest_idintentotest) REFERENCES intentotest(idintentotest);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_respuesta_pregunta') THEN
        ALTER TABLE respuesta
            ADD CONSTRAINT fk_respuesta_pregunta
            FOREIGN KEY (pregunta_idpregunta) REFERENCES pregunta(idpregunta);
    END IF;
END $$;

INSERT INTO registrador (
    activo, apellidos, contrasena, correo, fecharegistro, nombreusuario, nombres
)
SELECT
    TRUE,
    'del Sistema',
    'registrador123',
    'registrador@uam.edu.ni',
    NOW(),
    'registrador',
    'Registrador'
WHERE NOT EXISTS (
    SELECT 1 FROM registrador WHERE nombreusuario = 'registrador'
);

INSERT INTO testnumerico (activo, descripcion, nombre, tipotest)
SELECT TRUE,
       'Verifique si el resultado de cada suma es Verdadero (A) o Falso (B).',
       'Numerico Sumas',
       'SUMAS'
WHERE NOT EXISTS (
    SELECT 1 FROM testnumerico WHERE tipotest = 'SUMAS'
);

INSERT INTO testnumerico (activo, descripcion, nombre, tipotest)
SELECT TRUE,
       'Verifique si el resultado de cada multiplicacion es Verdadero (A) o Falso (B).',
       'Numerico Multiplicaciones',
       'MULTIPLICACIONES'
WHERE NOT EXISTS (
    SELECT 1 FROM testnumerico WHERE tipotest = 'MULTIPLICACIONES'
);

WITH datos(numero, operacion, resultado, correcta) AS (
    VALUES
        (3,  '23 + 46 + 57 + 38',      164,     'A'),
        (4,  '17 + 39 + 42 + 25',      113,     'B'),
        (5,  '56 + 49 + 77 + 94',      276,     'A'),
        (6,  '48 + 55 + 29 + 63',      195,     'A'),
        (7,  '64 + 37 + 99 + 58',      268,     'B'),
        (8,  '84 + 73 + 68 + 35',      250,     'B'),
        (9,  '95 + 83 + 47 + 36',      271,     'B'),
        (10, '54 + 87 + 96 + 19',      256,     'A'),
        (11, '18 + 27 + 76 + 89',      210,     'A'),
        (12, '98 + 89 + 32 + 74',      283,     'B'),
        (13, '86 + 79 + 92 + 67',      324,     'A'),
        (14, '68 + 75 + 44 + 16',      191,     'B'),
        (15, '99 + 77 + 92 + 57',      325,     'A'),
        (16, '73 + 31 + 97 + 24',      225,     'A'),
        (17, '26 + 86 + 68 + 79',      249,     'B'),
        (18, '523 + 742 + 687 + 864',  2826,    'B'),
        (19, '241 + 923 + 576 + 438',  2178,    'A'),
        (20, '326 + 489 + 718 + 993',  2526,    'A'),
        (21, '432 + 627 + 368 + 878',  2203,    'B'),
        (22, '156 + 283 + 939 + 855',  2243,    'B'),
        (23, '724 + 467 + 659 + 872',  2722,    'A'),
        (24, '234 + 999 + 876 + 363',  2374,    'B'),
        (25, '361 + 648 + 876 + 453',  2338,    'A'),
        (26, '273 + 942 + 357 + 834',  2406,    'A'),
        (27, '562 + 447 + 688 + 955',  2550,    'B')
),
refs AS (
    SELECT
        (SELECT idregistrador FROM registrador WHERE nombreusuario = 'registrador' ORDER BY idregistrador LIMIT 1) AS idregistrador,
        (SELECT idtestnumerico FROM testnumerico WHERE tipotest = 'SUMAS' ORDER BY idtestnumerico LIMIT 1) AS idtest
)
INSERT INTO pregunta (
    activa,
    fechacreacion,
    numeropregunta,
    operacion,
    respuestacorrecta,
    resultadomostrado,
    registrador_idregistrador,
    testnumerico_idtestnumerico
)
SELECT TRUE, NOW(), d.numero, d.operacion, d.correcta, d.resultado, r.idregistrador, r.idtest
FROM datos d
CROSS JOIN refs r
WHERE NOT EXISTS (
    SELECT 1
    FROM pregunta p
    WHERE p.testnumerico_idtestnumerico = r.idtest
      AND p.numeropregunta = d.numero
);

WITH datos(numero, operacion, resultado, correcta) AS (
    VALUES
        (30, '82 x 3',       246,     'A'),
        (31, '54 x 4',       206,     'B'),
        (32, '36 x 8',       298,     'B'),
        (33, '79 x 6',       474,     'A'),
        (34, '67 x 9',       603,     'A'),
        (35, '763 x 7',      5241,    'B'),
        (36, '546 x 4',      2284,    'B'),
        (37, '435 x 8',      3480,    'A'),
        (38, '984 x 6',      5804,    'B'),
        (39, '798 x 7',      5586,    'A'),
        (40, '3486 x 3',     11458,   'B'),
        (41, '4128 x 7',     29896,   'B'),
        (42, '5749 x 5',     28745,   'A'),
        (43, '2976 x 4',     12904,   'B'),
        (44, '9489 x 6',     56934,   'A'),
        (45, '43638 x 8',    349104,  'A'),
        (46, '53264 x 7',    373848,  'B'),
        (47, '36578 x 9',    329202,  'A'),
        (48, '26773 x 8',    214184,  'A'),
        (49, '66399 x 6',    397394,  'B'),
        (50, '624085 x 3',   1872255, 'A'),
        (51, '529724 x 5',   2649620, 'B'),
        (52, '478907 x 7',   3342349, 'B'),
        (53, '683218 x 8',   5465744, 'A'),
        (54, '732363 x 6',   4404178, 'B')
),
refs AS (
    SELECT
        (SELECT idregistrador FROM registrador WHERE nombreusuario = 'registrador' ORDER BY idregistrador LIMIT 1) AS idregistrador,
        (SELECT idtestnumerico FROM testnumerico WHERE tipotest = 'MULTIPLICACIONES' ORDER BY idtestnumerico LIMIT 1) AS idtest
)
INSERT INTO pregunta (
    activa,
    fechacreacion,
    numeropregunta,
    operacion,
    respuestacorrecta,
    resultadomostrado,
    registrador_idregistrador,
    testnumerico_idtestnumerico
)
SELECT TRUE, NOW(), d.numero, d.operacion, d.correcta, d.resultado, r.idregistrador, r.idtest
FROM datos d
CROSS JOIN refs r
WHERE NOT EXISTS (
    SELECT 1
    FROM pregunta p
    WHERE p.testnumerico_idtestnumerico = r.idtest
      AND p.numeropregunta = d.numero
);

COMMIT;

SELECT t.tipotest, COUNT(p.idpregunta) AS total_preguntas
FROM testnumerico t
LEFT JOIN pregunta p ON p.testnumerico_idtestnumerico = t.idtestnumerico
WHERE t.tipotest IN ('SUMAS', 'MULTIPLICACIONES')
GROUP BY t.tipotest
ORDER BY t.tipotest;
